const imagesPath = "/images/gallery";

export const GALLERY_IMAGES = [
  { src: `${imagesPath}/gallery_1.jpg` },
  { src: `${imagesPath}/gallery_2.jpg` },
  { src: `${imagesPath}/gallery_3.jpg` },
  { src: `${imagesPath}/gallery_4.jpg` },
  { src: `${imagesPath}/gallery_5.jpg` },
  { src: `${imagesPath}/gallery_6.jpg` },
  { src: `${imagesPath}/gallery_7.jpg` },
  { src: `${imagesPath}/gallery_8.jpg` },
  { src: `${imagesPath}/gallery_9.jpg` },
  { src: `${imagesPath}/gallery_10.jpg` },
  { src: `${imagesPath}/gallery_11.jpg` },
  { src: `${imagesPath}/gallery_12.jpg` },
  { src: `${imagesPath}/gallery_13.jpg` },
  { src: `${imagesPath}/gallery_14.jpg` },
  { src: `${imagesPath}/gallery_15.jpg` },
  { src: `${imagesPath}/gallery_16.jpg` },
  { src: `${imagesPath}/gallery_17.jpg` },
  { src: `${imagesPath}/gallery_18.jpg` },
  { src: `${imagesPath}/gallery_19.jpg` },
  { src: `${imagesPath}/gallery_20.jpg` },
  { src: `${imagesPath}/gallery_21.jpg` },
  { src: `${imagesPath}/gallery_22.jpg` },
  { src: `${imagesPath}/gallery_23.jpg` },
  { src: `${imagesPath}/gallery_24.jpg` },
  { src: `${imagesPath}/gallery_25.jpg` },
];
